version: '3.8'

services:
  # Nginx Web Server
  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    ports:
      - "0.0.0.0:3000:80"
      - "0.0.0.0:8443:443"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/conf.d/local.conf:/etc/nginx/conf.d/local.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./public:/var/www/html/public
      - ./certbot/www:/var/www/html/.well-known/acme-challenge
    depends_on:
      - php-fpm
    networks:
      - laravel_network

  # PHP-FPM 8.3
  php-fpm:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: laravel_php
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      - PHP_IDE_CONFIG=serverName=laravel.local
    depends_on:
      - mysql
      - redis
    networks:
      - laravel_network

  # MySQL 8.4 Database
  mysql:
    image: mysql:8.4
    container_name: laravel_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_DATABASE:-diarioobras}
      MYSQL_USER: ${DB_USERNAME:-laravel_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-laravel_pass}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - laravel_network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: laravel_redis
    volumes:
      - redis_data:/data
    networks:
      - laravel_network

  # Laravel Horizon
  horizon:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: laravel_horizon
    volumes:
      - .:/var/www/html
    command: php artisan horizon
    depends_on:
      - mysql
      - redis
    networks:
      - laravel_network

  # Node.js + Vite
  node:
    image: node:20-alpine
    container_name: laravel_node
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - node_modules:/var/www/html/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run build"
    networks:
      - laravel_network

  # Mailhog para desenvolvimento
  mailhog:
    image: mailhog/mailhog
    container_name: laravel_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - laravel_network

  # phpMyAdmin para gerenciar MySQL
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: ${DB_USERNAME:-laravel_user}
      PMA_PASSWORD: ${DB_PASSWORD:-laravel_pass}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
    depends_on:
      - mysql
    networks:
      - laravel_network

  # Certbot para SSL (Produção)
  certbot:
    image: certbot/certbot
    container_name: laravel_certbot
    volumes:
      - ./nginx/ssl:/etc/letsencrypt
      - ./certbot/www:/var/www/html/.well-known/acme-challenge
    command: certonly --webroot --webroot-path=/var/www/html/.well-known/acme-challenge --email ${CERTBOT_EMAIL:-admin@laravel.local} --agree-tos --no-eff-email -d ${DOMAIN_NAME:-laravel.local}
    networks:
      - laravel_network

volumes:
  mysql_data:
  redis_data:
  node_modules:


networks:
  laravel_network:
    driver: bridge
