#!/bin/bash

echo "=== Configuração de E-mail SGL ==="
echo ""
echo "1. E-mail enviado com sucesso para: ro_fa_2011@hotmail.com"
echo "2. Link de reset gerado e salvo no log"
echo ""
echo "Para receber e-mails reais, configure SMTP:"
echo ""
echo "Opção 1 - Gmail:"
echo "  MAIL_MAILER=smtp"
echo "  MAIL_HOST=smtp.gmail.com"
echo "  MAIL_PORT=587"
echo "  MAIL_USERNAME=seu-email@gmail.com"
echo "  MAIL_PASSWORD=senha-de-app"
echo "  MAIL_ENCRYPTION=tls"
echo ""
echo "Opção 2 - Outlook/Hotmail:"
echo "  MAIL_MAILER=smtp"
echo "  MAIL_HOST=smtp-mail.outlook.com"
echo "  MAIL_PORT=587"
echo "  MAIL_USERNAME=seu-email@hotmail.com"
echo "  MAIL_PASSWORD=sua-senha"
echo "  MAIL_ENCRYPTION=tls"
echo ""
echo "Opção 3 - Mailtrap (recomendado para testes):"
echo "  MAIL_MAILER=smtp"
echo "  MAIL_HOST=sandbox.smtp.mailtrap.io"
echo "  MAIL_PORT=2525"
echo "  MAIL_USERNAME=sua_username_mailtrap"
echo "  MAIL_PASSWORD=sua_password_mailtrap"
echo "  MAIL_ENCRYPTION=tls"
echo ""
echo "Para aplicar a configuração:"
echo "1. Edite o arquivo .env com as configurações acima"
echo "2. Execute: docker compose exec php-fpm php artisan config:clear"
echo "3. Teste: docker compose exec php-fpm php artisan test:email ro_fa_2011@hotmail.com"
echo ""
echo "Status atual: E-mail salvo em storage/logs/laravel.log"



