#!/bin/bash

echo "=== Configuração Mailtrap para SGL ==="
echo ""
echo "📧 Passos para configurar:"
echo ""
echo "1. Acesse: https://mailtrap.io"
echo "2. Crie uma conta gratuita"
echo "3. Vá em 'Email Testing' > Seu Inbox > 'SMTP Settings'"
echo "4. Selecione 'Laravel' como linguagem"
echo "5. Copie suas credenciais"
echo ""
echo "📝 Suas credenciais serão algo como:"
echo "   Username: 1a2b3c4d5e6f7g"
echo "   Password: 1a2b3c4d5e6f7g"
echo ""
echo "🔧 Para aplicar a configuração:"
echo "1. Edite o arquivo .env"
echo "2. Substitua as linhas de MAIL por:"
echo ""
echo "MAIL_MAILER=smtp"
echo "MAIL_HOST=sandbox.smtp.mailtrap.io"
echo "MAIL_PORT=2525"
echo "MAIL_USERNAME=SUA_USERNAME_AQUI"
echo "MAIL_PASSWORD=SUA_PASSWORD_AQUI"
echo "MAIL_ENCRYPTION=tls"
echo "MAIL_FROM_ADDRESS=\"noreply@sgl.com\""
echo "MAIL_FROM_NAME=\"SGL - Sistema de Gestão\""
echo ""
echo "3. Execute: docker compose exec php-fpm php artisan config:clear"
echo "4. Teste: docker compose exec php-fpm php artisan test:email ro_fa_2011@hotmail.com"
echo ""
echo "✅ Depois disso, todos os e-mails aparecerão no inbox do Mailtrap!"
echo ""
echo "📋 Template salvo em: .env.mailtrap.template"



